# Site settings
title: Zarin's Blog
header-img: img/home-bg.png
email: zarins23@gmail.com
copyright_name: zarins23
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Blogs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zarins23
learn_profile: zarins23
email_username: zarins23@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
